fix_seed: 0
checkpoints_every: 16
result_path: ./results_supcon
config_path: ./config.yaml

resume:
  resume: False
  resume_path: path/to/checkpoints.pth
  restart_optimizer: True

encoder:
  composition: esm_v2 # esm_v2, promprot, both
  model_type: esm_v2 # esm_v2, t5
  model_name:  facebook/esm2_t33_650M_UR50D # facebook/esm2_t33_650M_UR50D, esm2_t36_3B_UR50D, facebook/esm2_t30_150M_UR50D, facebook/esm2_t12_35M_UR50D, facebook/esm2_t6_8M_UR50D, Rostlab/prot_t5_base_mt_uniref50
  max_len: 1024
  num_classes: 8
  prm4prmpro: ppi
  frag_overlap: 200

PEFT: PFT #lora # FT, PFT, frozen, lora, PromT
decoder:
  combine: False #combine classification and motif?
  type: "cnn-linear" #"cnn" "linear" "cnn-linear"
  cnn_channel: 32
  cnn_kernel: 7
  droprate: 0.15

train_settings:
  dataloader: "batchsample" #"batchsample","clean"
  num_epochs: 15
  shuffle: True
  device: cuda:0
  batch_size: 16 #16
  grad_accumulation: 1
  loss_pos_weight: 35 #35
  additional_pos_weights: True
  loss_pos_weight_nucleus: 10
  loss_pos_weight_nucleus_export: 50
  dataset: v2 # v2, v3
  fine_tune_lr: -2 # -1, -2, -3
  log_every: 30
  data_aug:
    enable: True
    per_times: 5
    add_original: False
    neg_mutation_rate: 0.3
    pos_mutation_rate: 0.1



valid_settings:
  do_every: 1
  batch_size: 16
  device: cuda:0


predict_settings:
  batch_size: 16
  device: cuda:0
  cutoffs: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

optimizer:
  name: adam
  lr: 1e-4 #1e-2
  weight_decouple: True
  weight_decay: 1e-3 #0.0005
  eps: 1e-16
  beta_1: 0.9
  beta_2: 0.999
  use_8bit_adam: False
  grad_clip_norm: 1
  decay:
    warmup: 1024
    min_lr: 1e-5
    gamma: 0.2
    num_restarts: 1
    first_cycle_steps: 40500  #null before
  mode: cosine #skip, cosine

supcon:
  apply: False
  drop_out: 0.1
  n_pos: 2 #9
  n_neg: 2 #30
  temperature: 0.1
  hard_neg: False
  weight: 1
  warm_start: 0
  apply_supcon_loss: False #if False can still apply supcon sampling method, but no supcon loss!